http {
    include /etc/nginx/mime.types; # include the mime types configuration file to define the types of files that can be served by the server.

    server {
        listen 80;
        root /usr/share/nginx/html;

        absolute_redirect off;

        location /demofolder {
            root /usr/share/nginx/html;
        }

        rewrite ^/number/([0-9]+)$ /count/$1;

        location ~* /count/[0-9]+ {
            root /usr/share/nginx/html;
            # The ~* indicates a case-insensitive regular expression match for the location. In this case, it matches any URL that starts with /count/ followed by one or more digits. 
            try_files / =404;
        }

        location /demo2 {
            alias /usr/share/nginx/html/demofolder; # alias is used to map a URI to a different directory
        }

        location /vegetables {
            root /usr/share/nginx/html;
            try_files /vegetables/veggies.html /index.html =404;
            # try_files is used to check for the existence of files in the specified order and serve the first one found. If none are found, it returns a 404 error.
        }

        location /crops {
            return 307 /vegetables;
        }
    }
}

events {

}