http {
    include /etc/nginx/mime.types;

    server {
        listen 8000;
        root /usr/share/nginx/html;

        location /demofolder {
            root /usr/share/nginx/html;
        }
    }
}

events {

}